name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          filter: tree:0
          fetch-depth: 0
      
      - uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      
      - run: bun install --no-cache
      - uses: nrwl/nx-set-shas@v4.3.0

      - run: bun nx affected -t lint test build
